# Generated by Django 3.1.7 on 2021-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contactno', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('family_contact', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
