# Generated by Django 3.1.7 on 2021-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
    ]
