# Generated by Django 3.1.7 on 2021-03-16 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(max_length=20)),
                ('homeno', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('job_profession', models.CharField(blank=True, max_length=50)),
                ('job_address', models.CharField(blank=True, max_length=50)),
                ('vehicle_type', models.CharField(blank=True, max_length=20)),
                ('vehicle_no', models.CharField(blank=True, max_length=30)),
                ('blood_group', models.CharField(blank=True, max_length=30)),
                ('family_member_details', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=459)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(blank=True, default='default.jpg', upload_to='img/')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contactno', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(blank=True, default='default.jpg', upload_to='img/')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
    ]
