# Generated by Django 3.1.7 on 2021-04-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0009_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='photofile',
        ),
        migrations.AddField(
            model_name='videos',
            name='videofile',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
