# Generated by Django 3.1.7 on 2021-04-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0010_auto_20210402_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchman',
            name='profile_pic',
            field=models.FileField(blank=True, default='default.jpg', upload_to='img/'),
        ),
    ]
