# Generated by Django 3.1.7 on 2021-04-06 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0012_auto_20210403_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=35)),
                ('contact_no', models.CharField(max_length=20)),
                ('vm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetails')),
            ],
        ),
    ]
