# Generated by Django 3.1.7 on 2021-04-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0013_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='house_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
