# Generated by Django 3.1.7 on 2021-04-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0014_visitors_house_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='profile_pic',
            field=models.FileField(blank=True, default='avtar.png', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_pic',
            field=models.FileField(blank=True, default='avtar.png', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.FileField(blank=True, default='avtar.png', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photofile',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='watchman',
            name='profile_pic',
            field=models.FileField(blank=True, default='avtar.png', upload_to='img/'),
        ),
    ]
