# Generated by Django 3.1.7 on 2021-03-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchman', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchman',
        ),
    ]
